     <script src="<?php echo base_url(); ?>assets/vendors/js/vendor.bundle.base.js"></script> 
    <script src="<?php echo base_url(); ?>assets/vendors/jquery-bar-rating/jquery.barrating.min.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/chart.js/Chart.min.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/flot/jquery.flot.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/flot/jquery.flot.resize.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/flot/jquery.flot.categories.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/flot/jquery.flot.fillbetween.js"></script>
    <script src="<?php echo base_url(); ?>assets/vendors/flot/jquery.flot.stack.js"></script> 
    <script src="<?php echo base_url(); ?>assets/js/off-canvas.js"></script>
    <script src="<?php echo base_url(); ?>assets/js/hoverable-collapse.js"></script>
    <script src="<?php echo base_url(); ?>assets/js/misc.js"></script>
    <script src="<?php echo base_url(); ?>assets/js/settings.js"></script>
    <script src="<?php echo base_url(); ?>assets/js/todolist.js"></script> 
    <script src="<?php echo base_url(); ?>assets/js/dashboard.js"></script> 
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>